apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/elasticache.services.k8s.aws_cacheclusters.yaml
  - bases/elasticache.services.k8s.aws_cacheparametergroups.yaml
  - bases/elasticache.services.k8s.aws_cachesubnetgroups.yaml
  - bases/elasticache.services.k8s.aws_replicationgroups.yaml
  - bases/elasticache.services.k8s.aws_serverlesscaches.yaml
  - bases/elasticache.services.k8s.aws_snapshots.yaml
  - bases/elasticache.services.k8s.aws_users.yaml
  - bases/elasticache.services.k8s.aws_usergroups.yaml
