apiVersion: v1
name: elasticache-chart
description: A Helm chart for the ACK service controller for Amazon ElastiCache (ElastiCache)
version: 0.0.27
appVersion: 0.0.27
home: https://github.com/aws-controllers-k8s/elasticache-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/elasticache-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: ElastiCache Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/elasticache-maintainer
keywords:
  - aws
  - kubernetes
  - elasticache
